"""
Tools for the Copywriter agent — caption writing and hashtag selection.

These are lightweight LLM-assist tools. The actual writing is done by the
agent's LLM, but these tools help structure output and refine results.
"""

import logging
from agent_framework import FunctionTool
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------
# Input schemas
# ------------------------------------------------------------------

class WriteCaptionInput(BaseModel):
    topic: str = Field(..., description="The topic/subject of the post.")
    tone: str = Field(
        default="engaging",
        description="Desired tone: 'inspiring', 'funny', 'educational', 'provocative', 'casual', 'professional'.",
    )
    content_format: str = Field(
        default="image",
        description="Post format: 'image', 'carousel', 'reel', 'story'. Affects caption length.",
    )
    visual_description: str = Field(
        default="",
        description="Description of the media/visual so the caption complements it.",
    )
    target_audience: str = Field(
        default="",
        description="Who the post is for (e.g. 'fitness beginners', 'tech enthusiasts').",
    )
    hook_type: str = Field(
        default="",
        description="Preferred hook style: 'question', 'bold_statement', 'number_list', 'controversy'. Leave empty to auto-select.",
    )


class SuggestHashtagsInput(BaseModel):
    topic: str = Field(..., description="The topic to find hashtags for.")
    caption: str = Field(default="", description="The written caption for context.")
    count: int = Field(default=20, ge=5, le=30, description="Number of hashtags to suggest.")


class RefineCaptionInput(BaseModel):
    original_caption: str = Field(..., description="The current caption to refine.")
    feedback: str = Field(..., description="What to change or improve (e.g. 'make it funnier', 'shorter', 'add a question').")


# ------------------------------------------------------------------
# Tool functions
# ------------------------------------------------------------------

async def write_caption(
    topic: str,
    tone: str = "engaging",
    content_format: str = "image",
    visual_description: str = "",
    target_audience: str = "",
    hook_type: str = "",
) -> dict:
    """
    Structure and validate caption parameters.
    The actual caption text is generated by the agent's LLM using these inputs.
    """
    # Determine optimal caption length based on format
    length_guide = {
        "image": "medium (100-200 words)",
        "carousel": "long (150-300 words, educational)",
        "reel": "short (30-80 words)",
        "story": "very short (10-30 words)",
    }

    return {
        "status": "ready",
        "brief": {
            "topic": topic,
            "tone": tone,
            "format": content_format,
            "visual_description": visual_description,
            "target_audience": target_audience,
            "hook_type": hook_type or "auto-select best fit",
            "recommended_length": length_guide.get(content_format, "medium"),
            "instructions": (
                "Write the caption now. Start with a strong hook in the first line. "
                "Use line breaks for readability. End with a clear CTA. "
                "Do NOT include hashtags in the caption — they go separately."
            ),
        },
    }


async def suggest_hashtags(topic: str, caption: str = "", count: int = 20) -> dict:
    """
    Provide hashtag selection guidance.
    The actual hashtag list is generated by the agent's LLM.
    """
    return {
        "status": "ready",
        "brief": {
            "topic": topic,
            "caption_context": caption[:200] if caption else "N/A",
            "target_count": count,
            "distribution": {
                "broad_popular (1M+ posts)": f"{count // 4} hashtags",
                "medium (100K-1M posts)": f"{count // 2} hashtags",
                "niche (<100K posts)": f"{count - count // 4 - count // 2} hashtags",
            },
            "instructions": (
                "Generate the hashtag list now. Mix broad, medium, and niche hashtags. "
                "All lowercase, no spaces after #. Group them in a single paragraph."
            ),
        },
    }


async def refine_caption(original_caption: str, feedback: str) -> dict:
    """
    Refine an existing caption based on human or agent feedback.
    """
    return {
        "status": "ready",
        "original_caption": original_caption,
        "feedback": feedback,
        "instructions": (
            "Rewrite the caption incorporating the feedback. "
            "Keep the same general structure but apply the requested changes. "
            "Return the full updated caption."
        ),
    }


# ------------------------------------------------------------------
# Build tools list
# ------------------------------------------------------------------

def build_copywriter_tools() -> list[FunctionTool]:
    return [
        FunctionTool(
            name="write_caption",
            description="Prepare a caption brief with topic, tone, format, and audience. Then write the caption.",
            input_model=WriteCaptionInput,
            func=write_caption,
        ),
        FunctionTool(
            name="suggest_hashtags",
            description="Generate a set of 15-25 relevant hashtags (mix of popular, medium, and niche).",
            input_model=SuggestHashtagsInput,
            func=suggest_hashtags,
        ),
        FunctionTool(
            name="refine_caption",
            description="Rewrite/improve an existing caption based on feedback from human review.",
            input_model=RefineCaptionInput,
            func=refine_caption,
        ),
    ]
